# Generated by Django 4.1.2 on 2022-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="SteelworksUser",
        ),
    ]
