# Generated by Django 4.1.3 on 2022-12-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steelworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtimeuserpair',
            old_name='classes',
            new_name='gym_class',
        ),
    ]
