# Generated by Django 4.1.3 on 2022-12-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steelworks', '0002_rename_classes_classtimeuserpair_gym_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorUserPair',
        ),
    ]
