# Generated by Django 4.1.2 on 2022-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0002_rename_user_steelworksuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="steelworksuser",
            old_name="name",
            new_name="address_line_1",
        ),
        migrations.AddField(
            model_name="steelworksuser",
            name="first_name",
            field=models.CharField(default="name", max_length=240, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="steelworksuser",
            name="last_name",
            field=models.CharField(
                default="last name", max_length=240, verbose_name="Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="steelworksuser",
            name="phone",
            field=models.CharField(
                default=123456789, max_length=240, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
