# Generated by Django 4.1.2 on 2022-11-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0003_rename_name_steelworksuser_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steelworksuser",
            name="address_line_1",
            field=models.CharField(max_length=240, verbose_name="address_line_1"),
        ),
        migrations.AlterField(
            model_name="steelworksuser",
            name="first_name",
            field=models.CharField(max_length=240, verbose_name="first_name"),
        ),
        migrations.AlterField(
            model_name="steelworksuser",
            name="last_name",
            field=models.CharField(max_length=240, verbose_name="last_name"),
        ),
        migrations.AlterField(
            model_name="steelworksuser",
            name="phone",
            field=models.CharField(max_length=240, verbose_name="phone"),
        ),
    ]
