# Generated by Django 4.1.2 on 2022-11-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0004_alter_steelworksuser_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="steelworksuser",
            name="address_line_2",
            field=models.CharField(
                default="add 2", max_length=240, verbose_name="address_line_2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="steelworksuser",
            name="address_line_3",
            field=models.CharField(
                default="add 3", max_length=240, verbose_name="address_line_3"
            ),
            preserve_default=False,
        ),
    ]
