# Generated by Django 4.1.2 on 2022-11-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0005_steelworksuser_address_line_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="steelworksuser",
            name="postcode",
            field=models.CharField(
                default="pcode", max_length=240, verbose_name="postcode"
            ),
            preserve_default=False,
        ),
    ]
