# Generated by Django 4.1.2 on 2022-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0006_steelworksuser_postcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=240, verbose_name="product_name"),
                ),
                (
                    "product_cost",
                    models.CharField(max_length=240, verbose_name="product_cost"),
                ),
                (
                    "product_details",
                    models.CharField(max_length=240, verbose_name="product_details"),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
