# Generated by Django 4.1.2 on 2022-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0007_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUserPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=240, verbose_name="product_name"),
                ),
                (
                    "subscribed_users",
                    models.CharField(max_length=240, verbose_name="subscribed_users"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
