# Generated by Django 4.1.2 on 2022-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steelworks", "0010_remove_productuserpair_product_user_pair_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=240, verbose_name="first_name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=240, verbose_name="last_name"),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "address_line_1",
                    models.CharField(max_length=240, verbose_name="address_line_1"),
                ),
                (
                    "address_line_2",
                    models.CharField(max_length=240, verbose_name="address_line_2"),
                ),
                (
                    "address_line_3",
                    models.CharField(max_length=240, verbose_name="address_line_3"),
                ),
                ("postcode", models.CharField(max_length=240, verbose_name="postcode")),
                ("phone", models.CharField(max_length=240, verbose_name="phone")),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorUserPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("instructor", models.ManyToManyField(to="steelworks.instructor")),
                ("students", models.ManyToManyField(to="steelworks.steelworksuser")),
            ],
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(max_length=240, verbose_name="class_name"),
                ),
                (
                    "class_details",
                    models.CharField(max_length=240, verbose_name="class_details"),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "enrolled_students",
                    models.ManyToManyField(to="steelworks.steelworksuser"),
                ),
                ("instructor", models.ManyToManyField(to="steelworks.instructor")),
            ],
        ),
    ]
