# Generated by Django 4.1.3 on 2022-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelworks', '0012_remove_instructor_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoruserpair',
            name='instructor_name',
            field=models.CharField(default='no-instructor-name', max_length=240, verbose_name='instructor_name'),
        ),
    ]
