# Generated by Django 4.1.3 on 2022-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelworks', '0013_instructoruserpair_instructor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructoruserpair',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='instructoruserpair',
            name='instructor_email',
            field=models.CharField(default='no-instructor-email', max_length=240, verbose_name='instructor_name'),
        ),
    ]
